# Generated by Django 5.1.6 on 2025-05-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('entreprise', models.CharField(max_length=150)),
                ('type_service', models.CharField(max_length=100)),
                ('beneficiaire', models.CharField(max_length=150)),
                ('point_contact', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('satisfaction', models.CharField(max_length=50)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientIndividuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('prenoms_nom', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('type_service', models.CharField(max_length=100)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('satisfaction', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('date_enregistrement', models.DateField(blank=True, null=True)),
                ('prenoms_nom', models.CharField(max_length=150)),
                ('point_focal', models.CharField(max_length=100)),
                ('deja_contact', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
                ('date_dernier_contact', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
    ]
