# Generated by Django 5.1.6 on 2025-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('trainer', 'Formateur'), ('manager', 'Responsable'), ('admin', 'Administrateur'), ('other', 'Autre')], max_length=20)),
                ('hire_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('specialization', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
