# Generated by Django 5.1.6 on 2025-04-22 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviApprenant',
            fields=[
                ('ID_Apprenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='learners.learner')),
                ('Date_debut', models.DateField()),
                ('Date_fin', models.DateField()),
                ('Poste_avant_teelaf', models.CharField(max_length=255)),
                ('Poste_apres_teelaf', models.CharField(max_length=255)),
                ('Dernier_contact', models.DateField()),
                ('Commentaire', models.CharField(choices=[('Excellent', 'Excellent'), ('Très satisfait', 'Très satisfait'), ('Satisfait', 'Satisfait'), ('Assez satisfait', 'Assez satisfait'), ('Neutre', 'Neutre'), ('Moyennement satisfait', 'Moyennement satisfait'), ('Peu satisfait', 'Peu satisfait'), ('Insatisfait', 'Insatisfait'), ('Pas satisfait', 'Pas satisfait'), ('Très insatisfait', 'Très insatisfait'), ('Mauvais', 'Mauvais'), ('Inacceptable', 'Inacceptable')], default='Neutre', max_length=30)),
            ],
        ),
    ]
