# Generated by Django 5.1.6 on 2025-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('birth_date', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('O', 'Autre')], max_length=1, verbose_name='Sexe')),
                ('phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('statut', models.CharField(choices=[('Etudiants _ Elèves', 'Etudiants _ Elèves'), ('Entrepreneurs', 'Entrepreneurs'), ('Professionnels', 'Professionnels'), ('Sans emploi _ Au chômage', 'Sans emploi _ Au chômage')], default='Etudiants _ Elèves', max_length=30, verbose_name='Statut')),
                ('desired_course', models.CharField(max_length=100, verbose_name='Formation souhaitée')),
                ('observation', models.CharField(choices=[('Oui', 'Oui'), ('Non', 'Non')], default='Non', max_length=3, verbose_name='Observation')),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID Apprenant')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Date inscription')),
            ],
        ),
    ]
