# Generated by Django 5.1.6 on 2025-05-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('depense', 'Dépense'), ('recette', 'Recette'), ('formation', 'Formation'), ('autre', 'Autre')], max_length=20)),
                ('solde', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FraisFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom_nom', models.CharField(max_length=255)),
                ('date_inscription', models.DateField()),
                ('formation_suivie', models.CharField(max_length=255)),
                ('frais_formation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inscription', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('avance_payer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_fin', models.DateField()),
            ],
        ),
    ]
