# Generated by Django 5.1.6 on 2025-05-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Suivi_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('Quantite', models.PositiveIntegerField()),
                ('Utiliser', models.PositiveIntegerField()),
                ('En_stock', models.PositiveIntegerField()),
                ('Observation', models.TextField(blank=True, null=True)),
                ('Commentaire', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_et_zone', models.CharField(max_length=255)),
                ('Date_de_début', models.DateField()),
                ('Date_de_fin', models.DateField()),
                ('Budget_alloue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Depenses_reelles', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Subventions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Participants', models.TextField()),
                ('Beneficiaire', models.CharField(max_length=255)),
                ('Statuts', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
